# Generated by Django 5.2.6 on 2026-06-17 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIIDIIActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('fii_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fii_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fii_net', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('dii_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('dii_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('dii_net', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'verbose_name': 'FII/DII activity',
                'verbose_name_plural': 'FII/DII activity',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CorporateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BONUS', 'Bonus'), ('SPLIT', 'Split'), ('RIGHTS', 'Rights issue'), ('MERGER', 'Merger'), ('DEMERGER', 'Demerger'), ('ACQUISITION', 'Acquisition'), ('PROMOTER_STAKE', 'Promoter stake change'), ('CEO_RESIGN', 'CEO resigned'), ('CFO_RESIGN', 'CFO resigned'), ('AUDITOR_RESIGN', 'Auditor resigned'), ('SEBI_ACTION', 'SEBI action'), ('PROMOTER_SELL', 'Promoter selling'), ('PROMOTER_PLEDGE', 'Promoter pledge change')], db_index=True, max_length=30)),
                ('event_date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_events', to='symbols.symbol')),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['symbol', 'event_type', 'event_date'], name='market_data_symbol__eb2693_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('traded_qty', models.BigIntegerField(default=0)),
                ('delivery_qty', models.BigIntegerField(default=0)),
                ('delivery_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='symbols.symbol')),
            ],
            options={
                'verbose_name': 'Delivery daily',
                'verbose_name_plural': 'Delivery daily',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], default='NEUTRAL', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='symbols.symbol')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['symbol', 'published_at'], name='market_data_symbol__42c37e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OHLCVDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv', to='symbols.symbol')),
            ],
            options={
                'verbose_name': 'OHLCV daily',
                'verbose_name_plural': 'OHLCV daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='market_data_symbol__d6f7c3_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SectorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('return_1d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('return_5d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('return_20d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='symbols.sector')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('sector', 'date')},
            },
        ),
    ]
