"""NIFTY 50 constituents for MVP universe seeding."""

NIFTY_50 = [
    {"ticker": "ADANIENT", "name": "Adani Enterprises Ltd.", "sector": "Metals & Mining"},
    {"ticker": "ADANIPORTS", "name": "Adani Ports and SEZ Ltd.", "sector": "Services"},
    {"ticker": "APOLLOHOSP", "name": "Apollo Hospitals Enterprise Ltd.", "sector": "Healthcare"},
    {"ticker": "ASIANPAINT", "name": "Asian Paints Ltd.", "sector": "Consumer Durables"},
    {"ticker": "AXISBANK", "name": "Axis Bank Ltd.", "sector": "Financial Services"},
    {"ticker": "BAJAJ-AUTO", "name": "Bajaj Auto Ltd.", "sector": "Automobile"},
    {"ticker": "BAJFINANCE", "name": "Bajaj Finance Ltd.", "sector": "Financial Services"},
    {"ticker": "BAJAJFINSV", "name": "Bajaj Finserv Ltd.", "sector": "Financial Services"},
    {"ticker": "BPCL", "name": "Bharat Petroleum Corporation Ltd.", "sector": "Oil & Gas"},
    {"ticker": "BHARTIARTL", "name": "Bharti Airtel Ltd.", "sector": "Telecom"},
    {"ticker": "BRITANNIA", "name": "Britannia Industries Ltd.", "sector": "FMCG"},
    {"ticker": "CIPLA", "name": "Cipla Ltd.", "sector": "Healthcare"},
    {"ticker": "COALINDIA", "name": "Coal India Ltd.", "sector": "Metals & Mining"},
    {"ticker": "DIVISLAB", "name": "Divi's Laboratories Ltd.", "sector": "Healthcare"},
    {"ticker": "DRREDDY", "name": "Dr. Reddy's Laboratories Ltd.", "sector": "Healthcare"},
    {"ticker": "EICHERMOT", "name": "Eicher Motors Ltd.", "sector": "Automobile"},
    {"ticker": "GRASIM", "name": "Grasim Industries Ltd.", "sector": "Construction"},
    {"ticker": "HCLTECH", "name": "HCL Technologies Ltd.", "sector": "IT"},
    {"ticker": "HDFCBANK", "name": "HDFC Bank Ltd.", "sector": "Financial Services"},
    {"ticker": "HDFCLIFE", "name": "HDFC Life Insurance Company Ltd.", "sector": "Financial Services"},
    {"ticker": "HEROMOTOCO", "name": "Hero MotoCorp Ltd.", "sector": "Automobile"},
    {"ticker": "HINDALCO", "name": "Hindalco Industries Ltd.", "sector": "Metals & Mining"},
    {"ticker": "HINDUNILVR", "name": "Hindustan Unilever Ltd.", "sector": "FMCG"},
    {"ticker": "ICICIBANK", "name": "ICICI Bank Ltd.", "sector": "Financial Services"},
    {"ticker": "ITC", "name": "ITC Ltd.", "sector": "FMCG"},
    {"ticker": "INDUSINDBK", "name": "IndusInd Bank Ltd.", "sector": "Financial Services"},
    {"ticker": "INFY", "name": "Infosys Ltd.", "sector": "IT"},
    {"ticker": "JSWSTEEL", "name": "JSW Steel Ltd.", "sector": "Metals & Mining"},
    {"ticker": "KOTAKBANK", "name": "Kotak Mahindra Bank Ltd.", "sector": "Financial Services"},
    {"ticker": "LT", "name": "Larsen & Toubro Ltd.", "sector": "Construction"},
    {"ticker": "M&M", "name": "Mahindra & Mahindra Ltd.", "sector": "Automobile"},
    {"ticker": "MARUTI", "name": "Maruti Suzuki India Ltd.", "sector": "Automobile"},
    {"ticker": "NTPC", "name": "NTPC Ltd.", "sector": "Power"},
    {"ticker": "NESTLEIND", "name": "Nestle India Ltd.", "sector": "FMCG"},
    {"ticker": "ONGC", "name": "Oil & Natural Gas Corporation Ltd.", "sector": "Oil & Gas"},
    {"ticker": "POWERGRID", "name": "Power Grid Corporation of India Ltd.", "sector": "Power"},
    {"ticker": "RELIANCE", "name": "Reliance Industries Ltd.", "sector": "Oil & Gas"},
    {"ticker": "SBILIFE", "name": "SBI Life Insurance Company Ltd.", "sector": "Financial Services"},
    {"ticker": "SBIN", "name": "State Bank of India", "sector": "Financial Services"},
    {"ticker": "SUNPHARMA", "name": "Sun Pharmaceutical Industries Ltd.", "sector": "Healthcare"},
    {"ticker": "TCS", "name": "Tata Consultancy Services Ltd.", "sector": "IT"},
    {"ticker": "TATACONSUM", "name": "Tata Consumer Products Ltd.", "sector": "FMCG"},
    {"ticker": "TATAMOTORS", "name": "Tata Motors Ltd.", "sector": "Automobile"},
    {"ticker": "TATASTEEL", "name": "Tata Steel Ltd.", "sector": "Metals & Mining"},
    {"ticker": "TECHM", "name": "Tech Mahindra Ltd.", "sector": "IT"},
    {"ticker": "TITAN", "name": "Titan Company Ltd.", "sector": "Consumer Durables"},
    {"ticker": "ULTRACEMCO", "name": "UltraTech Cement Ltd.", "sector": "Construction"},
    {"ticker": "UPL", "name": "UPL Ltd.", "sector": "Chemicals"},
    {"ticker": "LTIM", "name": "LTIMindtree Ltd.", "sector": "IT"},
    {"ticker": "WIPRO", "name": "Wipro Ltd.", "sector": "IT"},
]
