# Generated by Django 5.2.6 on 2026-06-17 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.JSONField(default=dict)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='symbols.symbol')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['symbol', '-generated_at'], name='analysis_an_symbol__3e8775_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('bullish_prob', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bearish_prob', models.DecimalField(decimal_places=4, max_digits=6)),
                ('sideways_prob', models.DecimalField(decimal_places=4, max_digits=6)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=6)),
                ('model_version', models.CharField(default='xgboost-v0', max_length=50)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='symbols.symbol')),
            ],
            options={
                'ordering': ['-as_of_date'],
                'unique_together': {('symbol', 'as_of_date', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('warnings', models.JSONField(default=list)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='symbols.symbol')),
            ],
            options={
                'ordering': ['-as_of_date'],
                'unique_together': {('symbol', 'as_of_date')},
            },
        ),
    ]
