# Generated by Django 5.2.6 on 2026-06-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('metrics', models.JSONField(default=dict)),
                ('artifact_path', models.CharField(max_length=500)),
                ('feature_columns', models.JSONField(default=list)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
    ]
