# Generated by Django 5.2.6 on 2026-06-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_predictionmodelartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodelartifact',
            name='model_type',
            field=models.CharField(choices=[('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('catboost', 'CatBoost')], db_index=True, default='xgboost', max_length=20),
        ),
    ]
