# Generated by Django 5.2.6 on 2026-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_predictionmodelartifact_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
