# Generated by Django 5.2.6 on 2026-06-17 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('feature_group', models.CharField(choices=[('TECHNICAL', 'Technical'), ('VOLATILITY', 'Volatility'), ('FUNDAMENTAL', 'Fundamental'), ('CORPORATE_RISK', 'Corporate risk')], db_index=True, max_length=20)),
                ('features', models.JSONField(default=dict)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='symbols.symbol')),
            ],
            options={
                'ordering': ['-as_of_date'],
                'indexes': [models.Index(fields=['symbol', 'as_of_date'], name='features_fe_symbol__5aa4a7_idx')],
                'unique_together': {('symbol', 'as_of_date', 'feature_group')},
            },
        ),
    ]
