# Generated by Django 5.2.6 on 2026-06-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(db_index=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('roce', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('debt_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('profit_growth_yoy', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('revenue_growth_yoy', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='symbols.symbol')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('symbol', 'period_end')},
            },
        ),
    ]
